import { z } from 'zod';
import { OPTION_LIMITS } from '../config/options.ts';

/**
 * Wire format shared by the API client and the mock backend.
 * Every response is validated with these schemas before reaching the UI.
 */

export const endReasonSchema = z.enum(['timeUp', 'sunk']);

export const matchSettingsSchema = z.object({
  sessionTime: z
    .number()
    .int()
    .min(OPTION_LIMITS.sessionTime.min)
    .max(OPTION_LIMITS.sessionTime.max),
  spawnInterval: z
    .number()
    .min(OPTION_LIMITS.spawnInterval.min)
    .max(OPTION_LIMITS.spawnInterval.max),
});

export const matchSubmissionSchema = z
  .object({
    /** Generated by the client so retries never create duplicates. */
    id: z.string().min(8).max(64),
    playerId: z.string().min(8).max(64),
    captainName: z.string().trim().min(1).max(OPTION_LIMITS.captainName.maxLength),
    score: z.number().int().min(0),
    /** Seconds actually played. */
    duration: z.number().int().min(0),
    endReason: endReasonSchema,
    settings: matchSettingsSchema,
    playedAt: z.iso.datetime(),
  })
  .refine((match) => match.duration <= match.settings.sessionTime, {
    message: 'Duration cannot exceed the session time.',
    path: ['duration'],
  });

export const matchRecordSchema = matchSubmissionSchema;

export const submitResponseSchema = z.object({
  match: matchRecordSchema,
  /** Player's position in the ranking of this match's settings. */
  rank: z.number().int().min(1).nullable(),
});

export const rankingEntrySchema = z.object({
  rank: z.number().int().min(1),
  matchId: z.string(),
  playerId: z.string(),
  captainName: z.string(),
  score: z.number().int().min(0),
  playedAt: z.iso.datetime(),
});

export function pageSchema<T extends z.ZodType>(item: T) {
  return z.object({
    items: z.array(item),
    page: z.number().int().min(1),
    pageSize: z.number().int().min(1),
    total: z.number().int().min(0),
    totalPages: z.number().int().min(1),
  });
}

export const rankingPageSchema = pageSchema(rankingEntrySchema);
export const historyPageSchema = pageSchema(matchRecordSchema);

export type EndReasonDto = z.infer<typeof endReasonSchema>;
export type MatchSettingsDto = z.infer<typeof matchSettingsSchema>;
export type MatchSubmission = z.infer<typeof matchSubmissionSchema>;
export type MatchRecord = z.infer<typeof matchRecordSchema>;
export type SubmitResponse = z.infer<typeof submitResponseSchema>;
export type RankingEntry = z.infer<typeof rankingEntrySchema>;
export type RankingPage = z.infer<typeof rankingPageSchema>;
export type HistoryPage = z.infer<typeof historyPageSchema>;

export const PAGE_SIZE = 5;
